summit-set-mode: Added overlay retrieval
PROD-11256

diff --git a/package/summit-set-mode/files/set-mode b/package/summit-set-mode/files/set-mode
--- a/package/summit-set-mode/files/set-mode
+++ b/package/summit-set-mode/files/set-mode
@@ -22,38 +22,56 @@ prefix=$(echo "${default}" | sed -r 's/-[^-]+\.dtb//')
 # Find all parameters
 params=$(echo "${confs}" | sed -rn "s/.*${prefix}-(.*)\.dtbo.*/\1/p" | sort -u)
 
-if [ -z "${1}" ] ; then
-    echo "Usage: $0 <mode> [<mode> ...]"
-    echo "  <mode> is one or multiple of:"
-    echo "  default - remove all overlays"
-    echo "${params}" | sed 's/^/  /'
-    exit 1
-fi
+conf=
+cconf=$(fw_printenv -n conf)
 
-conf=''
-
-if [ "${1}" != "default" ] ; then
-    # If no parameters are found, exit
-    [ -z "${params}" ] && {
-        echo "No overlays found"
+case "${1}" in
+    '')
+        echo "Usage: $0 <mode> [<mode> ...]"
+        echo "  <mode> is one or multiple of:"
+        echo "  default - remove all overlays"
+        echo "  status - print active overlays"
+        echo "${params}" | sed 's/^/  /'
         exit 1
-    }
+        ;;
 
-    # Verify that all parameters are valid and add them into configuration string
-    for i in "${@}" ; do
-        echo "${params}" | grep -qFx "${i}" || {
-            echo "Invalid mode"
+    default)
+        # Remove all overlays
+        ;;
+
+    status)
+        # Print current configuration
+        if [ -z "${cconf}" ]; then
+            echo "No overlays set"
+        else
+            echo "Set overlays:"
+            echo "${cconf}" | tr '#' "\n" | sed -rn "s/${prefix}-(.*)\.dtbo/  \1/p"
+        fi
+        exit 0
+        ;;
+
+    *)
+        # If no parameters are found, exit
+        [ -z "${params}" ] && {
+            echo "No overlays found"
             exit 1
         }
-        conf="${conf}#${prefix}-${i}.dtbo"
-    done
 
-    # Add main configuration
-    [ -z "${conf}" ] || conf="#${default}${conf}"
-fi
+        # Verify that all parameters are valid and add them into configuration string
+        for i in "${@}" ; do
+            echo "${params}" | grep -qFx "${i}" || {
+                echo "Invalid mode"
+                exit 1
+            }
+            conf="${conf}#${prefix}-${i}.dtbo"
+        done
+
+        # Add main configuration
+        [ -z "${conf}" ] || conf="#${default}${conf}"
+        ;;
+esac
 
 # Verify that requested configuration is different from current one
-cconf=$(fw_printenv -n conf)
 if [ "${cconf}" = "${conf}" ] ; then
     echo "Configuration already set"
     exit 0
