Ran shell scripts through lint and fixed issues
PROD-10894

diff --git a/board/rootfs-additions-common/usr/bin/c_rehash b/board/rootfs-additions-common/usr/bin/c_rehash
--- a/board/rootfs-additions-common/usr/bin/c_rehash
+++ b/board/rootfs-additions-common/usr/bin/c_rehash
@@ -14,34 +14,31 @@
 #
 # contact: support@ezurio.com
 
-if [ ! $1 ]
-then
-	echo "Usage: $0 <pathname>"
+if [ -z "${1}" ]; then
+	echo "Usage: ${0} <pathname>"
 	exit
 fi
 
-if [ ! -d $1 ]
-then
-	echo "Error: Cannot find directory '$1'"
+if [ ! -d "${1}" ]; then
+	echo "Error: Cannot find directory '${1}'"
 	exit
 fi
 
-cd $1
+cd "${1}" || exit
 
 # Remove old hash files
 rm -f [0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z][0-9a-z].[0-9]*
 
 # Create hashes of each file, avoiding collisions with an incremental suffix
-ls -1 *.pem | while read cert_file
-do
-	hash=`openssl x509 -hash -noout -in $cert_file 2> /dev/null`
-	if [ $? = 0 ]
-	then
-		suffix=0
-		while [ -e $hash.$suffix ]
-		do
-			suffix=`expr $suffix + 1`
-		done
-		ln -s $cert_file $hash.$suffix
-	fi
+for cert_file in *.pem; do
+	[ -r "${cert_file}" ] || continue
+	[ -L "${cert_file}" ] && continue
+
+	hash=$(openssl x509 -hash -noout -in "${cert_file}" 2> /dev/null) || continue
+
+	suffix=0
+	while [ -e "${hash}.${suffix}" ]; do
+		suffix=$((suffix + 1))
+	done
+	ln -s "${cert_file}" "${hash}.${suffix}"
 done
diff --git a/board/wb50n_sysd/rootfs-additions/usr/bin/fw_update b/board/wb50n_sysd/rootfs-additions/usr/bin/fw_update
--- a/board/wb50n_sysd/rootfs-additions/usr/bin/fw_update
+++ b/board/wb50n_sysd/rootfs-additions/usr/bin/fw_update
@@ -62,10 +62,10 @@ shift $((OPTIND - 1))
 url="${1}"
 
 if [ "${o_method}" = complete ]; then
-    ${run_on_sd} || die "only 'full' or 'main' update methods supported when booting from flash"
+    ${run_on_sd} || die "only 'full' or 'main' update methods supported when booting from NAND flash"
     p_method=${o_method}
 else
-    ${run_on_sd} && die "only 'complete' update method supported when booting from sd card"
+    ${run_on_sd} && die "only 'complete' update method supported when booting from SD card"
     p_method=${o_method}-${o_side}
 fi
 
@@ -83,9 +83,9 @@ file://*)
     case "${url%:*}" in
     http|https|ftp)
         if [ -x /usr/bin/curl ]; then
-            /usr/bin/curl -LsfI ${url} || die "File ${url} not found"
+            /usr/bin/curl -LsfI "${url}" || die "File ${url} not found"
         elif [ -x /usr/bin/wget ]; then
-            /usr/bin/wget -T4 -t1 --spider -qO - ${url} || die "File ${url} not found"
+            /usr/bin/wget -T4 -t1 --spider -qO - "${url}" || die "File ${url} not found"
         fi
         ;;
     esac
@@ -111,13 +111,12 @@ complete*)
     [ -d /sys/class/ubi/ubi0 ] && ubidetach -d 0
 
     if ${o_factory}; then
-
         # Mark bad blocks if found
         while read -r line; do
             case "${line}" in
             *u-boot*)
                 mtd=${line%%:*}
-                nandtest -m /dev/${mtd} || die "NAND test failed"
+                nandtest -m "/dev/${mtd}" || die "NAND test failed"
                 ;;
             esac
         done < /proc/mtd
@@ -127,38 +126,38 @@ complete*)
             case "${line}" in
             *u-boot-spl*)
                 mtd=${line%%:*}
-                [ $(cat /sys/class/mtd/${mtd}/bad_blocks) -eq 0 ] || \
+                [ "$(cat "/sys/class/mtd/${mtd}/bad_blocks")" -eq 0 ] || \
                     die "Bad blocks found in ${mtd} \"u-boot-spl\" area"
                 ;;
             *u-boot-env-a*)
                 mtd=${line%%:*}
-                bad_a=$(cat /sys/class/mtd/${mtd}/bad_blocks)
+                bad_a=$(cat "/sys/class/mtd/${mtd}/bad_blocks")
                 ;;
             *u-boot-env-b*)
                 mtd=${line%%:*}
-                bad_b=$(cat /sys/class/mtd/${mtd}/bad_blocks)
+                bad_b=$(cat "/sys/class/mtd/${mtd}/bad_blocks")
                 ;;
             esac
         done < /proc/mtd
 
-        [ ${bad_a} -gt 0 -a ${bad_b} -gt 0 ] && \
+        [ "${bad_a}" -gt 0 ] && [ "${bad_b}" -gt 0 ] && \
             die "Bad blocks found in both u-boot-env areas"
 
         . erase_som_nand
     fi
 
     ubimtd=$(sed -n 's/^\(.*\):.*"ubi"$/\1/p' /proc/mtd)
-    [ -z "${ubimtd}" ] || ubiformat /dev/${ubimtd} -y
+    [ -z "${ubimtd}" ] || ubiformat "/dev/${ubimtd}" -y
     ;;
 esac
 
 case "${url}" in
 *://*)
-    ${download_cmd} | swupdate-client -e stable,${p_method} ${o_verbose} - || die ""
+    ${download_cmd} | swupdate-client -e "stable,${p_method}" ${o_verbose} - || die ""
     ;;
 
 *)
-    swupdate-client -e stable,${p_method} ${o_verbose} "${url}" || die ""
+    swupdate-client -e "stable,${p_method}" ${o_verbose} "${url}" || die ""
     ;;
 esac
 
